package com.company;

public class Palavras {

    public static String[] REMOVER = {

            "PODER",
            "JUDICIÁRIO",
            "DO",
            "ESTADO",
            "RIO",
            "DE",
            "JANEIRO",
            "DGJUR",
            "DEIGE",
            "PRODUTIVIDADE",
            "JUÍZES",
            "JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL",
            "MAIO", "JUNHO", "JULHO", "AGOSTO",
            "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO",
            "NOME",
            "AUDIÊNCIAS",
            "REALIZADAS",
            "CONCLUSÕES",
            "DECISÕES",
            "OUTRAS",
            "TERMINATIVAS",
            "DEPOIMENTOS",
            "DESPACHOS",
            "JÚRI",
            "PROCESSOS",
            "DECIDIDOS",
            "SENTENÇAS",
            "COM",
            "MÉRITO",
            "SEM",
            "HOMOLOGAÇÃO",
            "ACORDO",

           /* "PODER JUDICIÁRIO DO ESTADO DO RIO DE JANEIRO",
            "DGJUR DEIGE",
            "Produtividade",
            "de",
            "Juízes",
            "Maio",
            "Nome",
            "Audiências",
            "Realizadas",
            "Conclusões",
            "Decisões",
            "Outras",
            "Decisões",
            "Terminativas",
            "Depoimentos",
            "Despachos",
            "Júri",
            "Processos",
            "Decididos",
            "Sentenças",
            "com",
            "Mérito",
            "sem",
            "Homologação",
            "Acordo"*/
    };
}
